                        <select id="municipalityID" class="form-control" name="municipality" required>
                                            <option value="" selected>Choose...</option>
                                            <option value="Ajuy"> Ajuy </option>
                                            <option value="Alimodian"> Alimodian </option>
                                            <option value="Anilao"> Anilao </option>
                                            <option value="Badiangan"> Badiangan </option>
                                            <option value="Balasan"> Balasan </option>
                                            <option value="Banate"> Banate </option>
                                            <option value="Barotac Nuevo"> Barotac Nuevo </option>
                                            <option value="Barotac Viejo"> Barotac Viejo </option>
                                            <option value="Batad"> Batad </option>
                                            <option value="Bingawan"> Bingawan </option>
                                            <option value="Cabatuan"> Cabatuan </option>
                                            <option value="Calinog"> Calinog </option>
                                            <option value="Carles"> Carles </option>
                                            <option value="Concepcion"> Concepcion </option>
                                            <option value="Dingle"> Dingle </option>
                                            <option value="Dueñas"> Dueñas </option>
                                            <option value="Dumangas"> Dumangas </option>
                                            <option value="Estancia"> Estancia </option>
                                            <option value="Guimbal"> Guimbal </option>
                                            <option value="Igbaras"> Igbaras </option>
                                            <option value="Janiuay"> Janiuay </option>
                                            <option value="Lambunao"> Lambunao </option>
                                            <option value="Leganes"> Leganes </option>
                                            <option value="Lemery"> Lemery </option>
                                            <option value="Leon"> Leon </option>
                                            <option value="Maasin"> Maasin </option>
                                            <option value="Miag-ao"> Miag-ao </option>
                                            <option value="Mina"> Mina </option>
                                            <option value="New Lucena"> New Lucena </option>
                                            <option value="Oton"> Oton </option>
                                            <option value="Passi"> Passi </option>
                                            <option value="Pavia"> Pavia </option>
                                            <option value="Pototan"> Pototan </option>
                                            <option value="San Dionisio"> San Dionisio </option>
                                            <option value="San Enrique"> San Enrique </option>
                                            <option value="San Joaquin"> San Joaquin </option>
                                            <option value="San Miguel"> San Miguel </option>
                                            <option value="San Rafael"> San Rafael </option>
                                            <option value="Santa Barbara"> Santa Barbara </option>
                                            <option value="Tigbauan"> Tigbauan </option>
                                            <option value="Tubungan"> Tubungan </option>
                                            <option value="Zarraga"> Zarraga </option>
                                        </select>